config/routes.rb
Rails.application.routes.draw do

  resources :cards
  delete 'cards/destroy'
  
  resources :compras

  resources :comments

  resources :answers

  resources :logros

  resources :favors do
    get "mis_favores", on: :collection
    get "republicar", on: :member 
  end

  resources :postulations do 
    post "evaluar" , on: :member
    get "mis_postulaciones", on: :collection
    get "mis_postulaciones_resueltas", on: :collection
   
    post "evaluar1" , on: :member 
  end
  
  root 'home#index'
  
  devise_for :users, controllers: { registrations: "registrations" } 
  
  resources :users, only: [:show, :index]

end

app/models/postulation.rb
class Postulation < ActiveRecord::Base

	validates :descripcion, :presence => {:message => "Usted debe ingresar una descripcion"}
	validates :fecha, :presence => {:message => "Usted debe ingresar una fecha"}    
    belongs_to :favor
	belongs_to :user
	
end

app/controllers/postulations_controller.rb
class PostulationsController < ApplicationController


  def mis_postulaciones
    if user_signed_in?
      @my_postulations = current_user.postulations
    end
  end
  def mis_postulaciones_resueltas
    if user_signed_in?
      @my_postulations_concluidas = current_user.postulations.where("aceptar = true AND (cumplio = true)")
    end
  end

  def index
    #@postulation = Postulation.all.order(:id)
    #@postulation.favor = Favor.find(params[:id])
    
  end

  def new
     #@favor = Favor.find(params[:id])  
     @postulation = Postulation.new

  end

  def show
    @postulation = Postulation.find(params[:id])
    
        
  end

  def create
    #@favor = Favor.find(params[:id])    
    #(params[:postulation][:fecha] == nil) && 
    if  (params[:postulation][:fecha].to_date == nil)
        flash[:notice] = "Debe ingresar una fecha"
        redirect_to :back
    else
      if (params[:postulation][:fecha].to_date >= Date.today)
          @postulation= Postulation.new(params.require(:postulation).permit(:favor_id, :fecha, :descripcion ))
          @postulation.user = current_user
        if @postulation.save
          flash[:notice] = "Se ha postulado exitosamente."
          redirect_to :back
         # redirect_to favors_path
        else
          flash[:notice] = "Problemas en postulacion del logro, complete todos los campos."     
          redirect_to :back
        end
      else
        flash[:notice] = "La fecha es incorrecta "     
        redirect_to :back
    end
        
    end    
  end

  def update
    @postulation.update_attributes(params.require(:postulation).permit(:name))
     redirect_to favors_path
  end

  def destroy
    @postulation.destroy
  end

  def edit
    @postulation = Postulation.all.order(:id)
  end

 def evaluar
  @postulation = Postulation.find(params[:id])
  @postulation.update(aceptar:params[:aceptar], noaceptar:params[:noaceptar]) 
   @postulation.favor.update(estado: 1) 
  if params[:aceptar] == "true"    
   params[:noaceptar] == "false"        
   flash[:notice] = "Postulacion aceptada"      
  end   
 redirect_to :back 
end

def evaluar1
  @postulation = Postulation.find(params[:id])
  @postulation.update(cumplio:params[:cumplio])   
  @postulation.update(nocumplio:params[:nocumplio])
  user = @postulation.user  
  if params[:cumplio] == "true"
     flash[:notice] = "Esta postulacion se cumplio"
     user.puntos += 1
   else
     if params[:nocumplio] == "false"      
        flash[:alert] = "Esta postulacion no se cumplio "   
        user.puntos -= 2 
     end      
  end
  user.save 
  redirect_to :back  
 end

 
end

app/helpers/postulations_helper.rb
module PostulationsHelper
end

app/views/postulations/_postulationsIndex.html.erb
<div class="panel-group">
	<div class="col-md-12">
		<div class="panel panel-default">			
			<div class="panel-body">
				<font face="arial" size="6" color="black">
						Postulaciones:
				</font>	
				<div class="row">
					<div class="col-md-12">
					    <div class="panel panel-default">
        			        <div class="panel-body">	 	
								<table class="table table-hover">		
						 			<tr>
										<th>
											<font face="arial" size="4" color="Grey"> Descripcion </font>
										</th>

						                <th>
											<font face="arial" size="4" color="Grey"> Fecha de realizacion de la gauchada </font>
										</th>

										<th>
											<font face="arial" size="4" color="Grey"> Nombre y Apellido </font>
										</th>

										 <th>
										   <font face="arial" size="4" color="Grey"> Localidad  </font>
										 </th>

										 <th>
										   <font face="arial" size="4" color="Grey"> Cantidad de puntos  </font>
										 </th>

										 <th>
										   <font face="arial" size="4" color="Grey"> Logro  </font>
										 </th>

										 <th>
										   <font face="arial" size="4" color="Grey">   </font>
										 </th>

										 <th>
										   <font face="arial" size="4" color="Grey">   </font>
										 </th>
									</tr>
						            
			                        
									<% postulations = Favor.find(params[:id]).postulations.all.order(:id) %>
									<% postulations.each do |p| %>
									

									<tr> 
											<td>
												<font face="arial" size="3" color="black">
													<%= p.descripcion %>
												</font>
											</td>

						                    <td>
												<font face="arial" size="3" color="black">
													<%= p.fecha %>
												</font>
											</td>
										

											<td>
												<font face="arial" size="3" color="black">
													<%= p.user.name %>
													<%= p.user.apellido %>
												</font>
											</td>

						                    <td>
												<font face="arial" size="3" color="black">
													<%= p.user.localidad%>
												</font>
											</td>
						                     
						                    <td>
												<font face="arial" size="3" color="black">
													<%= p.user.puntos %>
												</font>
											</td> 

											<td>
												<font face="arial" size="3" color="black">
													<%= p.user.logro.nombre %>
												</font>
											</td>
			                                   
				                            <% if p.aceptar == true %>
			                             
											     <td> 								         
											          <font face="calibri" size="4" color="black"> Aceptaste esta postulacion! contacta al usuario <%= p.user.email %>  </font>
											     </td>
										 
											<% end %> 						    
											 		
						                    
						                    <% if p.fecha >= Date.today  && p.aceptar == false  %>
											 	
													<td> <%= link_to "Aceptar",evaluar_postulation_path(p, aceptar: "true"), method: :post, class: 'btn btn-info btn-sm', data: { confirm: 'Esta seguro de aceptar esta postulacion?' } %>
													 </td>
											<% end %> 
										</tr> 

									<% end %>	
							    </table>
					
                            </div>
                        </div>
                    </div>
                </div>

			</div>
		</div>
	</div>
</div>

app/views/postulations/_selectedPostulation.html.erb
 <div class="panel-group">
	<div class="col-md-12">
		<div class="panel panel-default">			
			<div class="panel-body">
				<font face="arial" size="6" color="black">
						Postulaciones:
				</font>	
				<div class="row">
					<div class="col-md-12">
					    <div class="panel panel-default">
        			        <div class="panel-body">

								<table class="table table-hover">		
						 			<tr>
										<th>
											<font face="arial" size="4" color="black"> Descripcion </font>
										</th>

						                <th>
											<font face="arial" size="4" color="black"> Fecha de realizacion de la gauchada </font>
										</th>

										<th>
											<font face="arial" size="4" color="black"> Nombre y Apellido </font>
										</th>

										 <th>
										   <font face="arial" size="4" color="black"> Localidad  </font>
										 </th>

										 <th>
										   <font face="arial" size="4" color="black"> Cantidad de puntos  </font>
										 </th>

										 <th>
										   <font face="arial" size="4" color="black"> Logro  </font>
										 </th>									  

										  
									</tr>
						            
			                        
									<% p = Favor.find(params[:id]).postulations.all.order(:id).find_by(aceptar: true)  %>
									

									<tr> 
											<th>
												<font face="arial" size="3" color="Grey">
													<%= p.descripcion %>
												</font>
											</th>

						                    <th>
												<font face="arial" size="3" color="Grey">
													<%= p.fecha %>
												</font>
											</th>
										

											<th>
												<font face="arial" size="3" color="Grey">
													<%= p.user.name %>
													<%= p.user.apellido %>
												</font>
											</th>

						                    <th>
												<font face="arial" size="3" color="Grey">
													<%= p.user.localidad%>
												</font>
											</th>
						                     
						                    <th>
												<font face="arial" size="3" color="Grey">
													<%= p.user.puntos %>
												</font>
											</th> 

											<th>
												<font face="arial" size="3" color="Grey">
													<%= p.user.logro.nombre %>
												</font>
											</th> 
											
			                                
									</tr>
									<tr> 
									    
											<div class="col-md-12">
											    <div class="panel-body">				
					                                  <table class="table table-hover">
                                                     <th>  
						                                  <% if p.aceptar == true %>
													          <font face="arial" size="4" color="black"> Aceptaste esta postulación! contacta al usuario:  <font face="arial" size="4" color="orange"> <%= p.user.email %> </font> </font>	
														  <% end %> 						    
											        </th>	
 													<th>
                                                    </th>
                                                    <th>
                                                    </th>
                                                    <th>
                                                    </th>
                                                    <th>
                                                    </th>
                                                    <th>
                                                    </th>	
					                                <th>  
							                            <% if p.aceptar == true && p.cumplio == false %>           	
							                        																									
															<%= link_to "Cumplio",evaluar1_postulation_path(p, cumplio: "true"), method: :post, class: 'btn btn-info btn-sm' , data: { confirm: 'Esta seguro de que este usuario cumplio su palabra ?' } %>	
															            		
																														
															<%= link_to "No Cumpliò", evaluar1_postulation_path(p, nocumplio:  "false"), method: :post ,class: 'btn btn-success btn-sm' , data: { confirm: 'Esta seguro de que este usuario no cumplio su palabra?' } %> 
														
											 		    <% end %>
													</th>

										
										   <th>
			                                <% if p.nocumplio == false %>                                  
						                            <td>                  
												     <font face="calibri" size="4" color="Red"> Este usuario no cumplio su palabra, puedes republicar el favor!  <%= link_to "Republica tu favor", republicar_favor_path(p.favor) %> </font>
											    	</td>
											<% end %>								
											<% if p.cumplio == true %>                               
				                                   <td> 
				                                    <% p.nocumplio = false %>		                                    
													<font face="calibri" size="4" color="green"> Este usuario cumplio su palabra </font>
												   </td>
				                            <% end %>
				                            </th>
                                         
									                 </table> 
									            </div>
									     </div>
									       
									</tr>										
										
							    </table>
                            </div>
                        </div>
                    </div>
                </div>

			</div>
		</div>
	</div>
</div>

app/views/postulations/create.html.erb
<h1>Postulations#create</h1>
<p>Find me in app/views/postulations/create.html.erb</p>

app/views/postulations/destroy.html.erb
<h1>Postulations#destroy</h1>
<p>Find me in app/views/postulations/destroy.html.erb</p>

app/views/postulations/edit.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-md-10">

	<div class="jumbotron"> 
		

        <p>


        </p>
		
		<font face="arial" size="6" color="black">
			Listado de personas postuladas
		</font>
		
		<p>

		</p>  
  		<table class="table">

 			<tr>
				

				<th>
					<font face="arial" size="5" color="orange"> Email del usuario </font>
				</th>

				<th>
					<font face="arial" size="5" color="orange"> Nombre del usuario  </font>
				</th>


				
			</tr>
            
			<% @postulation.each do |p| %>

				<tr> 
					
					<td>
						<font face="arial" size="3" color="black">
							<%= p.user.email%>
						</font>
					</td>

					<td>
						<font face="arial" size="3" color="black">
							<%= p.user.name %>
							<%= p.user.apellido %>
						</font>
					</td>
					

				</tr> 
	
			<% end %>

		</table>
		<p>
			<a class="btn btn-warning btn-lg" href="/" role="button"> Volver </a>
		</p> 
	</div>	
</div>

app/views/postulations/index.html.erb
<%= render "postulations/postulationsIndex" %>

app/views/postulations/mis_postulaciones.html.erb
<% if user_signed_in? %>
	<div class="col-md-10">
		<div class="panel panel-default">
			<div class="panel-body">
				<h1 class="text-center">
					 <font color="orange"> Mis postulaciones </font>
				</h1>
				<div class="row">
		            <table class="table table-hover">
		            	<% if @my_postulations.empty? %>
			  				<font face="arial" size="6" color="black">
								Todavía no te postulaste a ningun favor
							</font>
				 		<% else %>
			                <tr>
			                	<th>
			                        <font face="arial" size="4" color="grey"> Imagen </font>
			                    </th>
			                    <th>
			                        <font face="arial" size="4" color="grey"> Titulo </font>
			                    </th>
			                    <th>
			                        <font face="arial" size="4" color="grey"> Detalle </font>
			                    </th>
			                    <th>
			                        <font face="arial" size="4" color="grey"> Ciudad </font>
			                    </th>
			                    <th>
			                        <font face="arial" size="4" color="grey"> Descripcion de postulacion </font>
			                    </th>
			                    <th>
			                        <font face="arial" size="4" color="grey"> Fecha </font>
			                    </th>
			                    <th>
			                        <font face="arial" size="4" color="grey"> Estado </font>
			                    </th>
			                </tr>
			                
			                <% @my_postulations.each do |p| %>
			                    <tr>
			                        <td>
			                            <font face="arial" size="3" color="black">
			                                <%= image_tag p.favor.imagen, size: '50x50' %>
			                            </font>
			                        </td>
			                        <td>
			                            <font face="arial" size="3" color="black">
			                                <%= p.favor.titulo %>
			                            </font>
			                        </td>
			                        <td>
			                            <font face="arial" size="3" color="black">
			                                <%= p.favor.descripcion.truncate(50) %>
			                            </font>
			                        </td>
			                        <td>
			                            <font face="arial" size="3" color="black">
			                                <%= p.favor.localidad %>
			                            </font>
			                        </td> 
			                        <td>
			                            <font face="arial" size="3" color="black">
			                                <%= p.descripcion %>
			                            </font>
			                        </td>
			                        <td>
			                            <font face="arial" size="3" color="black">
			                                <%= p.fecha.day %>/<%= p.fecha.month %>/<%= p.fecha.year %>
			                            </font>
			                        </td>
			                         <td>
			                            <font face="arial" size="3" color="black">
			                            	
			                            	<% if (p.fecha < Date.today) && (p.favor.estado == 0) %>                  		
			                            		 
							                        <font face="arial" size="4" color="black"> Postulacion vencida </font>
							                    
			                            	<% end %>

			                                <% if (p.favor.estado == 0) && (p.fecha >= Date.today) && p.noaceptar == true  %>
			                               		
							                    <font face="arial" size="4" color="grey">Pendiente </font>
							                    
			                                <% end %>

			                                <% if p.aceptar == true && p.cumplio == false%> 

							                    <font face="arial" size="4" color="green"> Aceptado </font>	
							                    <font face="arial" size="4" color="black"> Ponete en contacto con el dueño de la gauchada <%= p.favor.user.email%> </font>	                    
			                            	<% end %>

		                            		<% if p.aceptar == true && p.cumplio == true %>  

			                                    <font face="arial" size="4" color="blue">Cumplido</font>

				                            <% end %>
				                            
			                                <% if p.aceptar == true && p.nocumplio == false %> 

			                                	<font face="arial" size="4" color="brown">No cumpliste este favor</font> 

			                                <% end %>

			                                <% if p.favor.estado == 1 && p.noaceptar == true %>
			                                	<font face="arial" size="4" color="red">Rechazado</font> 
			                                <% end %>
	                                        
			                            </font>
			                        </td>
			                        <td>
		                                <font face="arial" size="3" color="black"> 
		                                    <%= link_to "Ver detalle", p.favor %>
		                                </font>
		                            </td>                    
			                    </tr>
			                <% end %>
			            <% end %>     
		            </table>		        
				</div>
			</div>
		</div>
	</div>
<% end %>	

app/views/postulations/mis_postulaciones_resueltas.html.erb
<% if user_signed_in? %>
	<div class="col-md-10">
		<div class="panel panel-default">
			<div class="panel-body">
				<h1 class="text-center">
					 <font color="black"> Favores resueltos: </font>
				</h1>
				<% if @my_postulations_concluidas != nil %>
					<% if @my_postulations_concluidas.count > 0 %>
						<div class="row">
				            <table class="table table-hover">
				                <tr>
				                	<th>
				                        <font face="arial" size="4" color="grey"> Imagen </font>
				                    </th>
				                    <th>
				                        <font face="arial" size="4" color="grey"> Titulo </font>
				                    </th>
				                    <th>
				                        <font face="arial" size="4" color="grey"> Detalle </font>
				                    </th>
				                    <th>
				                        <font face="arial" size="4" color="grey"> Ciudad </font>
				                    </th>
				                    <th>
				                        <font face="arial" size="4" color="grey"> Descripcion de postulacion </font>
				                    </th>
				                </tr>
				                
				                <% @my_postulations_concluidas.each do |p| %>
				                    <tr>
				                        <td>
				                            <font face="arial" size="3" color="black">
				                                <%= image_tag p.favor.imagen, size: '50x50' %>
				                            </font>
				                        </td>
				                        <td>
				                            <font face="arial" size="3" color="black">
				                                <%= p.favor.titulo %>
				                            </font>
				                        </td>
				                        <td>
				                            <font face="arial" size="3" color="black">
				                                <%= p.favor.descripcion.truncate(50) %>
				                            </font>
				                        </td>
				                        <td>
				                            <font face="arial" size="3" color="black">
				                                <%= p.favor.localidad %>
				                            </font>
				                        </td> 
				                        <td>
				                            <font face="arial" size="3" color="black">
				                                <%= p.descripcion %>
				                            </font>
				                        </td>
				                        <td>
				                            <font face="arial" size="3" color="black">
				                                <%= p.fecha %>
				                            </font>
				                        </td>
				                        <td>
			                                <font face="arial" size="3" color="black"> 
			                                        <%= link_to "Ver detalle", p.favor %>
			                                </font>
			                            </td>                    
				                    </tr>
				                <% end %>    
				            </table>		        
						</div>
					<% else %>
						<p> </p>
	                    <p> </p>
	                    <h1 class="text-center">  Hasta el momento no has resuelto ninguna gauchada. </h1>
	                    <p> </p>
	                    <p> </p> 
			    	<% end %> 
				<% else %>
                	<p> </p>
                    <p> </p>
                    <h1 class="text-center">  Hasta el momento no has resuelto ninguna gauchada. </h1>
                    <p> </p>
                    <p> </p> 
			    <% end %> 
			</div>
		</div>
	</div>
<% end %>	

app/views/postulations/update.html.erb
<h1>Postulations#update</h1>
<p>Find me in app/views/postulations/update.html.erb</p>