config/routes.rb
Rails.application.routes.draw do

  resources :cards
  delete 'cards/destroy'
  
  resources :compras

  resources :comments

  resources :answers

  resources :logros

  resources :favors do
    get "mis_favores", on: :collection
    get "republicar", on: :member 
  end

  resources :postulations do 
    post "evaluar" , on: :member
    get "mis_postulaciones", on: :collection
    get "mis_postulaciones_resueltas", on: :collection
   
    post "evaluar1" , on: :member 
  end
  
  root 'home#index'
  
  devise_for :users, controllers: { registrations: "registrations" } 
  
  resources :users, only: [:show, :index]

end

app/models/compra.rb
class Compra < ActiveRecord::Base
	belongs_to :card
	include ActiveModel::Validations
	validates :cantidad_de_puntos, :presence => {:message => "Usted debe ingresar la cantidad de puntos a comprar."},:numericality => {:message =>  "Error!Sólo de admiten valores numéricos para la cantidad de puntos a comprar."} 
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  def get_compra
  end

  def new
    @compra = Compra.new
  end

  def index
    if params[:fecha_inf].present? and params[:fecha_sup].present? 
      if params[:fecha_inf] > params[:fecha_sup]
        flash[:alert] = "Error. La fecha superior debe ser posterior a la fecha inferior. Re-ingrese las fechas."
        @testigo = false
      else
        @testigo = true
        if params[:fecha_inf].to_date > Date.today  
          flash[:alert] = "Error. La fecha superior no puede ser superior a la fecha actual. Re-ingrese la fecha superior."
          @testigo = false
          render :index
        else
          @compras_a_sumar = Compra.where('created_at >= ?',"%#{params[:fecha_inf].to_date.beginning_of_day}%")
        end
        if params[:fecha_sup].to_date > Date.today
            flash[:alert] = "Error. La fecha superior no puede ser superior a la fecha actual. Re-ingrese la fecha superior."
            @testigo = false
            render :index
        else
            if @compras_a_sumar != nil 
              @compras_a_sumar = @compras_a_sumar.where('created_at <= ?',"%#{params[:fecha_sup].to_date.to_date.end_of_day}%")
            else
              @compras_a_sumar = Compra.where('created_at <= ?',"%#{params[:fecha_sup].to_date}%")
            end
        end
      end
    else
      @testigo = false
    end
  end

  def show
  end

  def edit
  end

  def create
    @compra = Compra.new(params.require(:compra).permit(:cantidad_de_puntos,:user_id,:card_id))
    if @compra.save
      current_user.puntos= current_user.puntos + @compra.cantidad_de_puntos
      current_user.save
      @plata=@compra.cantidad_de_puntos * 12
      flash[:notice] = "Se ha realizado la compra de #{@compra.cantidad_de_puntos} puntos exitosamente,se debitaron $#{@plata} de su tarjeta de crédito."
      current_user.cards.each do |l|
        if l.recordar == false
          current_user.cards.find(l.id).destroy
        end
      end
      redirect_to favors_path
    else
      flash[:notice] = "Problemas en la realización de la compra."
      render :new
    end
  end

  def update
  end

  def destroy
  end
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/views/compras/create.html.erb
<h1>Compras#create</h1>
<p>Find me in app/views/compras/create.html.erb</p>

app/views/compras/destroy.html.erb
<h1>Compras#destroy</h1>
<p>Find me in app/views/compras/destroy.html.erb</p>

app/views/compras/edit.html.erb
<h1>Compras#edit</h1>
<p>Find me in app/views/compras/edit.html.erb</p>

app/views/compras/get_compra.html.erb
<h1>Compras#get_compra</h1>
<p>Find me in app/views/compras/get_compra.html.erb</p>

app/views/compras/index.html.erb
<% if user_signed_in? %>
     <% if current_user.admin? %>
		<div class="col-md-6 col-md-4 list group">  
		  	<div class="panel-group">
		    	<div class="panel panel-default">   
		      		<div class="panel-body">
		      			<%= link_to "Volver inicio", root_path, class: 'btn btn-info btn-xs' %>
		          		<h1 class="text-center"> Menú de ganancias </h1>
		          		<p> </p>
						<h4> Ingrese la fecha de inicio y fin del intervalo en el que se quiere calcular las ganancias: </h4>
						<p> </p>
		    			<%= form_tag compras_path, method: :get do %>
		    				<div class="input-group">
			    				<h5> -Límite inferior: </h5>
			  					<%= date_field_tag :fecha_inf , "", maxlength: 8, class: "form-control", required: true %>
			  					<p> </p>
			  					<p> </p>
			  					<h5> -Límite superior: </h5>
				  				<%= date_field_tag :fecha_sup , Time.now.strftime('%Y-%m-%d') ,class: "form-control" , :cols => 2, :rows => 1, required: true %>
				  			</div>
				  			
		  					<%= submit_tag "Calcular", name: nil, class: "btn btn-primary btn-md"%>
		  				<% end %>
				       	<% if (@compras_a_sumar != nil) %>
			          		<% tot=0 %>
			          		<% @compras_a_sumar.each do |c| %>
			          			<tr>
									<td> <% tot=tot+c.cantidad_de_puntos*12 %> </td>
								</tr>
							<% end %>
						<% end %>
						<p> </p>
			  			<p> </p>
			  			<% if @testigo == true %>
							<%=  "Ganancias computadas entre las fechas: $ #{tot}.00"  %>
						<% end %>
		              <p> </p> 
		    		</div>	
		    	</div>
		  	</div>
		</div>
	<% end %>
<% end %>

app/views/compras/new.html.erb
<% if user_signed_in? %> 
  <div class="col-md-6 col-md-4 list group">  
    <div class="panel-group">
      <div class="panel panel-default">   
        <div class="panel-body">
            <h1 class="text-center"> Realizar compra de puntos </h1> 
  		      <%= link_to "Volver al inicio", root_path, class: 'btn btn-info btn-xs' %> 
              <p> </p>
              <p> </p> 
            <li> ¡Disponer de puntos te permite pedir gauchadas!. </li>
            <li> El valor de cada punto es de $12. </li>
            <li> También podes conseguir puntos realizando gauchadas a otros usuarios. </li>
  		      <%= form_for(@compra) do |f| %>
              <% if current_user.cards.count > 0 %>
                <div class="row">
                  <div class="col-md-4">
                    <%= f.label :"Cantidad de puntos :" %>
                    <%= f.text_field :cantidad_de_puntos, class: 'form-control', label: 'Cantidad de puntos', :cols => 3, :rows => 1 %>
                  </div>
                </div>
                <p> </p>
                <div class="row">
                  <div class="col-lg-8 ">
                    <%= f.label :"Modo_de_pago:" %>
                    <div class="panel panel-default ">
                      <p> </p>
                      <%= f.label :"Seleccione una de sus tarjetas registradas:" %>
                      <p> </p>
                      <%= f.label :"Número de tarjeta:" %>
                      <%= f.collection_select :card_id, current_user.cards.all, :id, :numero %>   
                      <p> </p>   
                  <% else %>
                    <%= f.label :"Usted no dispone de ninguna tarjeta de crédito registrada." %>
                  <% end %>
                  <p> </p> 
                    <%= link_to "Ingresar una nueva tarjeta",new_card_path, class: 'btn btn-info btn-sm ' %>
                    <p> </p> 
                </div>
              </div>
            <p> </p>
            </div>
              <% if current_user.cards.count > 0 %>
                <p> </p>
                <%= f.submit "Confirmar compra", class: 'btn btn-primary' %>
                <p> </p>    
              <%end%>
            <% if @compra.errors.any? %>
              <ul>
                <% @compra.errors.each do |atributo, mensaje| %>
                  <li> <%= mensaje %> </li>
                <% end %>
              </ul>
            <% end %>
          <% end %>
  	    </div>
      </div>
    </div>
  </div>
<%end%>

app/views/compras/update.html.erb
<h1>Compras#update</h1>
<p>Find me in app/views/compras/update.html.erb</p>