config/routes.rb
Rails.application.routes.draw do

  resources :cards
  delete 'cards/destroy'
  
  resources :compras

  resources :comments

  resources :answers

  resources :logros

  resources :favors do
    get "mis_favores", on: :collection
    get "republicar", on: :member 
  end

  resources :postulations do 
    post "evaluar" , on: :member
    get "mis_postulaciones", on: :collection
    get "mis_postulaciones_resueltas", on: :collection
   
    post "evaluar1" , on: :member 
  end
  
  root 'home#index'
  
  devise_for :users, controllers: { registrations: "registrations" } 
  
  resources :users, only: [:show, :index]

end

app/models/logro.rb
class Logro < ActiveRecord::Base
    has_many :users
    include ActiveModel::Validations  #necesario para agregar las condiciones de validacion
    validates :nombre, :presence => {:message => "Usted debe ingresar un nombre"}, :uniqueness => {:message => "Error. El nombre de logro elegido ya existe, elija otro nombre."}
	validates :descripcion, :presence => {:message => "Usted debe ingresar una descripcion"}
	validates :limite_inferior_rango, :presence => {:message => "Usted debe ingresar un límite inferior"}, :uniqueness => {:message => "Error. El límite inferior de logro elegido ya existe, elija otro límite inferior."}, :numericality => {:message =>  "Error!Sólo de admiten valores numéricos para los rangos."}
	validates :limite_superior_rango, :presence => {:message => "Usted debe ingresar una límite superior"}, :uniqueness => {:message => "Error. El límite superior de logro elegido ya existe, elija otro límite superior."}, :numericality => {:message =>  "Error!Sólo de admiten valores numéricos para los rangos."}
	validate :rango_menor_que_mayor
	def rango_menor_que_mayor
		if (limite_inferior_rango > limite_superior_rango)
			errors.add(:rango, "El límite inferior del rango debe ser menor al límite superior.")
		end
	end
	default_scope -> { order :limite_inferior_rango }
end

app/controllers/logros_controller.rb
  class LogrosController < ApplicationController
  before_action :get_logro, only: [:edit, :update, :destroy, :show, :marcar]

  def get_logro
    @logro = Logro.find(params[:id])
  end
  def new
    @logro = Logro.new
  end
    
  def index
    @logro = Logro.all
  end

  def show
    @logro = Logro.find(params[:id])
  end

  def edit
  end

  def create
    @logro = Logro.new(params.require(:logro).permit(:nombre,:descripcion,:marca, :limite_inferior_rango,:limite_superior_rango))
    if @logro.save
      flash[:notice] = "Se ha creado el logro exitosamente."
      render :index
    else
      flash[:notice] = "Problemas en la creación del logro."
      render :new
    end
  end
    #re
    #require(:nombre, :limite_inferior_rango, :limite_superior_rango, :marca).permit(:estado, :logro_id))
  def update
    if @logro.update_attributes(params.require(:logro).permit(:nombre,:descripcion,:marca, :limite_inferior_rango,:limite_superior_rango))
      flash[:notice] = "Se ha editado el logro exitosamente."
      redirect_to logros_path
    else
      flash[:notice] = "Problemas en la edición del logro."
      render 'edit'
    end
  end
  def marcar
    @logro.marca=false
    @logro.save
    redirect_to logros_path
  end

  def destroy
    if @logro.users.count!=0
      if @logro.marca
        @logro.marca=false
      else
        @logro.marca=true
      end
      @logro.save
    else
      @logro.destroy
    end
    redirect_to logros_path
  end
end

app/helpers/logros_helper.rb
module LogrosHelper
end

app/views/logros/create.html.erb
<h1>Logros#create</h1>
<p>Find me in app/views/logros/create.html.erb</p>
<% if @logro.errors.any? %>
   <ul>
      <% @logro.errors.each do |atributo, mensaje| %>
      <li> <%= mensaje %> </li>
      <% end %>
   </ul>
  <% flash[:notice] = "No se creó logro!"%>
<% end %>

app/views/logros/destroy.html.erb
<h1>Logros#destroy</h1>
<p>Find me in app/views/logros/destroy.html.erb</p>

app/views/logros/edit.html.erb
<div class="col-md-6 col-md-4 list group">  
  <div class="panel-group">
    <div class="panel panel-default">   
      <div class="panel-body">
        <h1 class="text-center"> Editar Logro </h1> 
        <%= link_to "Volver al menú de logros", logros_path, class: 'btn btn-info btn-xs' %>
        <%= form_for(@logro) do |f| %> 
          <div class="row">
            <div class="col-md-3">
              <%= f.label :logro_nombre, 'Nombre' %>
              <%= f.text_field :nombre, class: 'form-control', label: 'Nombre', :cols => 5, :rows => 1 %>
            </div>
          </div>
          <p> </p>
          <div class="row">
            <div class="col-md-5">
              <%= f.label :descripcion %>
              <%= f.text_area :descripcion, class: 'form-control', label: 'Descripcion', placeholder: 'Ingrese la descripcion' %>
            </div>
          </div>
          <p> </p>
          <div class="row">
              <div class="col-md-4">
                <%= f.label :rango_de_puntos %>
                <%= f.text_field :limite_inferior_rango, class: 'form-control', label: 'limite_inferior_rango' , placeholder: 'Límite   inferior' %>
                <%= f.text_field :limite_superior_rango, class: 'form-control', label: 'limite_superior_rango', placeholder: 'Límite superior' %>
              </div>
            </div>
          <div class='row'>
            <div class="col-md-3">
              <%= f.label :'categoría activa' %><br>
              <%= f.check_box :marca, label: 'categoría activa', checked:"checked" %>
            </div>
          </div> 
          <%= f.submit "Guardar logro", class: 'btn btn-primary' %>
          <% if @logro.errors.any? %>
              <ul>
                <% @logro.errors.each do |atributo, mensaje| %>
                  <li> <%= mensaje %> </li>
                <% end %>
              </ul>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/logros/get_logro.html.erb
<h1>Logros#get_logro</h1>
<p>Find me in app/views/logros/get_logro.html.erb</p>

app/views/logros/index.html.erb
<% if user_signed_in? %>
     <% if current_user.admin? %>
			<div class="panel-group">
				<div class="col-md-10 col-md-4 list group">
					<div class="panel panel-default">		
						<div class="panel-body">
							<h1 class="text-center"> Menú de Logros </h1>
							<table class="table">
								<tr>
									<th> Nombre </th>
									<th> Descripción </th>
									<th> Límite inferior </th>
									<th> Límite superior  </th>
									<th> Estado </th>
								</tr>	
								<% @conflictos=false %>
								<% @discontinuidad=false %>

								<% logros = Logro.all %>
								<% if logros.count != 0 %>
									<% @inf_ant=logros.first.limite_inferior_rango %>
								<% end %>
								<% @sup_ant=@inf_ant %>
								<% logros.each do |l| %>
									<tr>
										<td> <%= l.nombre %> </td>
											<td> <%= l.descripcion %> </td>	
											<% if l.limite_inferior_rango != nil %>
												<% if l.limite_inferior_rango < @sup_ant %>
														<td><FONT COLOR=red>  ¡<%= l.limite_inferior_rango %>!*  </FONT></td>
														<% @conflictos=true %>
												<% else %>
													<% if l.limite_inferior_rango != @sup_ant %>
														<td><FONT COLOR=orange>  ¡<%= l.limite_inferior_rango %>!*  </FONT></td>
														<% @discontinuidad=true %>
													<% else %>
														<td> <%= l.limite_inferior_rango %> </td>
													<% end %>	
												<% end %>
												<td> <%= l.limite_superior_rango %> </td>
												<% if l.users.count!=0 %>
													<% if l.marca %>
														<div class="col-md-5">
															<td> <%= "Activo    " %> </td>
														</div>
														<div class="col-md-5">  
															<td> <%= link_to "Desactivar", l,method: :delete, class: 'btn btn-warning btn-sm' %> </td>
														</div>
													<% else %>
														<div class="col-md-5">
															<td> <%= "Desactivado" %> </td>
														</div>
														<div class="col-md-5">
															<td> <%= link_to "Activar", l,method: :delete, class: 'btn btn-success btn-sm' %> </td>
											 			</div>
													<% end %>
												<% else %>
													<% if l.marca %>
														<div class="col-md-5">
															<td> <%= "Activo    " %> </td>
														</div>
													<% else %>
														<div class="col-md-5">
															<td> <%= "Desactivado" %> </td>
														</div>
													<% end %>
													<div class="col-md-5">
														<td> <%= link_to "Eliminar", l,method: :delete, class: 'btn btn-danger	 btn-sm' %> </td>
												 	</div>
												<% end %>
												<% @inf_ant=l.limite_inferior_rango %>
												<% @sup_ant=l.limite_superior_rango %>			
												<td>
													<%= link_to "Editar",edit_logro_path(l), class: 'btn btn-info btn-sm' %>
							   					</td>
											</tr>
										<% end %>
									<% end %>
								</table>
							<h1 class="text-center"> <%= link_to "Crear nuevo logro", new_logro_path, class: 'btn btn-info btn-lg' %> </h1>
							<% if @conflictos %>
								<p> <FONT COLOR=red>  Error! Los rangos de puntos de los logros (*) se superponen.  </FONT> </p>
							<% end %>
							<% if @discontinuidad %>
								<p> <FONT COLOR=orange>  Advertencia! Los rangos de puntos de los logros (*) no son continuos.  </FONT> </p>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	<% end %>

app/views/logros/marcar.html.erb
<h1>Logros#marcar</h1>
<p>Find me in app/views/logros/marcar.html.erb</p>

app/views/logros/new.html.erb
<% if current_user.singed
    <div class="col-md-6 col-md-4 list group">  
      <div class="panel-group">
        <div class="panel panel-default">   
          <div class="panel-body">
              <h1 class="text-center"> Crear nuevo Logro </h1> 
              <%= link_to "Volver al menú de logros", logros_path, class: 'btn btn-info btn-xs' %>
              <%= form_for(@logro) do |f| %>
                <div class="row">
                  <div class="col-md-3">
                    <%= f.label :nombre %>
                    <%= f.text_field :nombre, class: 'form-control', label: 'Nombre', :cols => 5, :rows => 1 %>
                  </div>
                </div>
                <p> </p>
                <div class="row">
                  <div class="col-md-6">
                    <%= f.label :descripcion %>
                    <%= f.text_area :descripcion, class: 'form-control', label: 'Descripcion', placeholder: 'Ingrese la descripcion' %>
                  </div>
                </div>
                <p> </p>
                <div class="row">
                  <div class="col-md-4">
                    <%= f.label :rango_de_puntos %>
                    <%= f.text_field :limite_inferior_rango, class: 'form-control', label: 'limite_inferior_rango' , placeholder: 'Límite   inferior' %>
                    <%= f.text_field :limite_superior_rango, class: 'form-control', label: 'limite_superior_rango', placeholder: 'Límite superior' %>
                  </div>
                </div>
                <div class='row'>
                  <div class="col-md-5">
                    <%= f.label :'categoría activa' %>
                    <%= f.check_box :marca, label: 'categoría activa', checked:"checked" %>
                  </div>
                </div> 
                <%= f.submit "Crear logro", class: 'btn btn-primary' %>
                <% if @logro.errors.any? %>
                  <ul>
                    <% @logro.errors.each do |atributo, mensaje| %>
                      <li> <%= mensaje %> </li>
                    <% end %>
                  </ul>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

app/views/logros/show.html.erb
<h1>Logros#show</h1>
	<% @logro.each do |n| %>
	<p> <%= n.nombre %> </p>
	<p> <%= n.limite_inferior_rango %> </p>
<% end %> 

app/views/logros/update.html.erb
<h1>Logros#update</h1>
<p>Find me in app/views/logros/create.html.erb</p>
<% if @logro.errors.any? %>
   <ul>
      <% @logro.errors.each do |atributo, mensaje| %>
      <li> <%= mensaje %> </li>
      <% end %>
   </ul>
  <% flash[:notice] = "No se editó logro!"%>
<% end %>