config/routes.rb
Rails.application.routes.draw do

  resources :cards
  delete 'cards/destroy'
  
  resources :compras

  resources :comments

  resources :answers

  resources :logros

  resources :favors do
    get "mis_favores", on: :collection
    get "republicar", on: :member 
  end

  resources :postulations do 
    post "evaluar" , on: :member
    get "mis_postulaciones", on: :collection
    get "mis_postulaciones_resueltas", on: :collection
   
    post "evaluar1" , on: :member 
  end
  
  root 'home#index'
  
  devise_for :users, controllers: { registrations: "registrations" } 
  
  resources :users, only: [:show, :index]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :user
	belongs_to :comment
	
	validates :detalle, presence: true, length: { minimum: 2}

	default_scope { order(created_at: :asc) }
end

app/models/card.rb
class Card < ActiveRecord::Base
	@año_actual=Time.now.strftime("%Y").to_i
	belongs_to :user
	has_many :compras	
	include ActiveModel::Validations  #necesario para agregar las condiciones de validacion
    validates :nombre, :presence => {:message => "Usted debe ingresar el tipo de tarjeta. Ej: Cabal."}
	validates :anio_vencimiento, :presence => {:message => "Usted debe ingresar el año de vencimiento de la tarjeta."},:numericality => {:message =>  "Error!Sólo de admite valor numéricos para el año."}, :numericality => { :greater_than_or_equal_to => @año_actual, :message => "Se ha ingresado un año de vencimiento inferior al año actual."} 
	validates :mes_vencimiento, :presence => {:message => "Usted debe ingresar el mes de vencimiento de la tarjeta."}, :numericality => {:message =>  "Error!Sólo de admite valor numéricos para el mes."}, :numericality => { :less_than_or_equal_to => 12, :message => "Se ha ingresado un mes de vencimiento inválido."},:numericality => { :greater_than_or_equal_to => 1, :message => "Se ha ingresado un mes de vencimiento inválido."}
	validates :nombre_prop, :presence => {:message => "Usted debe ingresar el nombre del titular."}
	validates :apellido_prop, :presence => {:message => "Usted debe ingresar el apelido del titular."}
	validates :cod_seguridad, :presence => {:message => "Usted debe ingresar el código de seguridad de la tarjeta."}, :numericality => {:message =>  "Error! El código de seguridad solo admite valores numéricos."}, length: {is: 3, :message =>  "Error! El códgio de seguridad debe contener 3 números." }
	validates :dni_titular, :presence => {:message => "Usted debe ingresar el DNI del titular."},:numericality => {:message =>  "Error! Caracteres inválidos para el DNI"},length: {is: 8, :message =>  "Error! El DNI debe contener exactamente 8 números." }	
	validate :formato_numero_tarjeta
	validate :tarjeta_existe_aleatorio
	def formato_numero_tarjeta
		@mensaje=false
		if (((numero[0,4]=~/\D/) != nil) or ((numero[5,4]=~/\D/) != nil) or ((numero[10,4]=~/\D/) != nil) or ((numero[15,4]=~/\D/)!= nil))
			@mensaje=true
		end
		if ((numero[4]!="-") or (numero[4]!="-") or (numero[4]!="-") or (numero[4]!="-")) 
			@mensaje=true
		end
		if @mensaje==true
			errors.add(:formato_erroneo, "Error! El formato de numero de tarjeta debe ser XXXX-XXXX-XXXX-XXXX.")
		end	
	end
	def tarjeta_existe_aleatorio
		if (numero[18]=="0") 
			errors.add(:tarjeta_existe_aleatorio, "Error! La tarjeta ingresada no existe, intente nuevamente.")
		end
	end
end
#, :numericality => {:message =>  "Error!Sólo de admite un valor numérico para el año de vencimiento."}
#:message => "El año de vencimiento debe ser igual o mayor al año actual"

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :favor
	belongs_to :user

	has_many :answers, dependent: :destroy
	
	validates :detalle, presence: true, length: { minimum: 4}

	default_scope { order(created_at: :desc) }
end

app/models/compra.rb
class Compra < ActiveRecord::Base
	belongs_to :card
	include ActiveModel::Validations
	validates :cantidad_de_puntos, :presence => {:message => "Usted debe ingresar la cantidad de puntos a comprar."},:numericality => {:message =>  "Error!Sólo de admiten valores numéricos para la cantidad de puntos a comprar."} 
end

app/models/favor.rb
class Favor < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :postulations, dependent: :destroy

	validates_presence_of :descripcion
	validates :imagen, :format => URI::regexp(%w(http https))
		
	validates :titulo, presence: true, length: { minimum: 4 }
	validates :localidad, presence: true, length: { minimum: 4 }
	#has_many :preguntas
end

app/models/logro.rb
class Logro < ActiveRecord::Base
    has_many :users
    include ActiveModel::Validations  #necesario para agregar las condiciones de validacion
    validates :nombre, :presence => {:message => "Usted debe ingresar un nombre"}, :uniqueness => {:message => "Error. El nombre de logro elegido ya existe, elija otro nombre."}
	validates :descripcion, :presence => {:message => "Usted debe ingresar una descripcion"}
	validates :limite_inferior_rango, :presence => {:message => "Usted debe ingresar un límite inferior"}, :uniqueness => {:message => "Error. El límite inferior de logro elegido ya existe, elija otro límite inferior."}, :numericality => {:message =>  "Error!Sólo de admiten valores numéricos para los rangos."}
	validates :limite_superior_rango, :presence => {:message => "Usted debe ingresar una límite superior"}, :uniqueness => {:message => "Error. El límite superior de logro elegido ya existe, elija otro límite superior."}, :numericality => {:message =>  "Error!Sólo de admiten valores numéricos para los rangos."}
	validate :rango_menor_que_mayor
	def rango_menor_que_mayor
		if (limite_inferior_rango > limite_superior_rango)
			errors.add(:rango, "El límite inferior del rango debe ser menor al límite superior.")
		end
	end
	default_scope -> { order :limite_inferior_rango }
end

app/models/postulation.rb
class Postulation < ActiveRecord::Base

	validates :descripcion, :presence => {:message => "Usted debe ingresar una descripcion"}
	validates :fecha, :presence => {:message => "Usted debe ingresar una fecha"}    
    belongs_to :favor
	belongs_to :user
	
end

app/models/rango_fecha.rb
class RangoFecha < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  has_many :compra
  has_many :cards
  #belongs_to :logro

  has_many :postulations, dependent: :destroy
  has_many :favors, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :answers, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 

  validates :name, presence: true, length: { minimum: 3 }
	validates :apellido, presence: true, length: { minimum: 3 }
	validates :telefono, presence: true, length: { minimum: 3 }
	validates :localidad, presence: true, length: { minimum: 3 }
	validates :dni, presence: true, uniqueness: true, length: {is: 8}
	validates_numericality_of :dni, :message => "Debe ingresar numeros"


  def logro
    logro = Logro.where("limite_inferior_rango <= ? AND limite_superior_rango >= ?", self.puntos, self.puntos).take
    return logro unless logro.nil?
    Logro.where("limite_superior_rango < ?", self.puntos).order(:limite_superior_rango).last
  end
	
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/favors_helper.rb
module FavorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logros_helper.rb
module LogrosHelper
end

app/helpers/mensajes_helper.rb
module MensajesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/puntos_helper.rb
module PuntosHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default"> 
	<div class="col-xs-12 col-md-12"> <%= link_to root_path do %>
			<%= image_tag "http://fotos.subefotos.com/2d78bdf0c0a8935f9afa3dce01cd47c8o.png", title:"Gauchada",class:"img-responsive", size: '2000x2000'%>
			<% end %>
	</div>
	<div class="container-fluid">
		<div class="row">
		    <div class="col-md-9">
		        <% if user_signed_in? %>
		            <td> <P ALIGN=left>
	            	<h0>
		            	<font face="arial" size="4" color="brown">
							<%= current_user.name %> <%= current_user.apellido %>						
						</font>
					</h0>
				<% end %>			
		    </div>
		  	<div class="col-md-3"> 
		  		<% if user_signed_in? %>
		  			<%= link_to "Modificar mis datos",edit_user_registration_path %>
					<%= link_to "Cerrar Sesión", destroy_user_session_path, method:'delete' , class:'btn btn-default' %>
				<% else %>
					<%= link_to "Iniciar Sesión", new_user_session_path , class:'btn btn-default' %>
					<%= link_to "Registrarme","/users/sign_up", class:'btn btn-default'%>
				<% end %>		
			</div>
		</div>
	</div>
</nav>



app/views/layouts/_lateral.html.erb
<% if user_signed_in? %>
	<div class="col-md-2  list group">
		<div class="panel-group">
			<% if current_user.admin? %>
				<div class="panel panel-default">
					<div class="panel-body">
						<font face="arial" size="5" color="orange">
							<p>
								Menú administrador:
							</p>
						</font>
						<p> <%= link_to "Menú de Logros", logros_path %> </p>
						<p> <%= link_to "Ver reportes de ganancias", compras_path %> </p>
						<p> <%= link_to "Ver ranking de usuarios", users_path %> </p> </p>

					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-body">
						<font face="arial" size="5" color="orange">
							<p>
								Menú usuario:
							</p>
						</font>
						<p> <%= link_to "Inicio", root_path %> </p>
						<p> <%= link_to "Mis gauchadas", mis_favores_favors_path %> </p>
						<p> <%= link_to "Comprar puntos",new_compra_path %> </p>
						<p> <%= link_to "Mis gauchadas resueltas",mis_postulaciones_resueltas_postulations_path %> </p>
						<p> <%= link_to "Mis postulaciones",mis_postulaciones_postulations_path %> </p>
					</div>
				</div>
			<% else %>
				<div class="panel panel-default">
					<div class="panel-body">
						<p> <%= link_to "Inicio", root_path %> </p>
						<p> <%= link_to "Mis gauchadas", mis_favores_favors_path %> </p>
						<p> <%= link_to "Comprar puntos", new_compra_path %> </p>
						<p> <%= link_to "Mis gauchadas resueltas",mis_postulaciones_resueltas_postulations_path %> </p>
		
						<p> <%= link_to "Mis postulaciones",mis_postulaciones_postulations_path %> </p>			
					</div>
				</div>
			<% end %>
		</div>
	</div>
<% end %>

app/views/layouts/application.html.erb
	<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" href="http://download.seaicons.com/download/i2969/ariil/alphabet/ariil-alphabet-letter-g.ico">
    <title>Gauchada</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/lateral" %>


    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
  
</html>